package http

import (
	"bytes"
	"strings"

	yaml "go.yaml.in/yaml/v4"
)

type preseedDirective struct {
	owner    string
	template string
	dtype    string
	value    string
	raw      string
}

// dcOutput is the dedicated emit-only output view (NOT debianConfigSpec, whose
// scalars lack omitempty and whose sudoMode would emit `sudo: 0`).
type dcOutput struct {
	Hostname    string      `yaml:"hostname,omitempty"`
	Domain      string      `yaml:"domain,omitempty"`
	Locale      string      `yaml:"locale,omitempty"`
	Timezone    string      `yaml:"timezone,omitempty"`
	Keyboard    string      `yaml:"keyboard,omitempty"`
	Mirror      *dcMirror   `yaml:"mirror,omitempty"`
	Network     *dcNetwork  `yaml:"network,omitempty"`
	Accounts    *dcAccounts `yaml:"accounts,omitempty"`
	Packages    []string    `yaml:"packages,omitempty"`
	Disk        *dcDisk     `yaml:"disk,omitempty"`
	LateCommand string      `yaml:"late_command,omitempty"`
	RawPreseed  string      `yaml:"raw_preseed,omitempty"`
}

type dcMirror struct {
	Hostname  string `yaml:"hostname,omitempty"`
	Directory string `yaml:"directory,omitempty"`
	Proxy     string `yaml:"proxy,omitempty"`
}

type dcNetwork struct {
	Interface string    `yaml:"interface,omitempty"`
	Static    *dcStatic `yaml:"static,omitempty"`
}

type dcStatic struct {
	Address     string   `yaml:"address,omitempty"`
	Netmask     string   `yaml:"netmask,omitempty"`
	Gateway     string   `yaml:"gateway,omitempty"`
	Nameservers []string `yaml:"nameservers,omitempty"`
}

type dcAccounts struct {
	RootPasswordHash string  `yaml:"root_password_hash,omitempty"`
	User             *dcUser `yaml:"user,omitempty"`
}

type dcUser struct {
	Fullname          string   `yaml:"fullname,omitempty"`
	Username          string   `yaml:"username,omitempty"`
	PasswordHash      string   `yaml:"password_hash,omitempty"`
	SSHAuthorizedKeys []string `yaml:"ssh_authorized_keys,omitempty"`
	// sudo intentionally absent: reverse keeps ssh/sudo verbatim in late_command.
}

type dcDisk struct {
	Devices      []string `yaml:"devices,omitempty"`
	RAID         string   `yaml:"raid,omitempty"`
	Layout       string   `yaml:"layout,omitempty"`
	Filesystem   string   `yaml:"filesystem,omitempty"`
	BootDegraded *bool    `yaml:"boot_degraded,omitempty"`
	ExpertRecipe string   `yaml:"expert_recipe,omitempty"`
}

// parsePreseed splits a flat d-i preseed into logical directives. It joins
// backslash line-continuations, drops blank lines and '#' comments, and splits
// each logical line into owner/template/type/value. A line that does not fit the
// `owner template type [value]` grammar is preserved verbatim as a passthrough
// directive (template == "") so nothing is ever dropped.
func parsePreseed(src []byte) []preseedDirective {
	var out []preseedDirective
	var buf strings.Builder
	joining := false
	for _, raw := range strings.Split(string(src), "\n") {
		line := raw
		// A physical line ending in '\' continues onto the next.
		if strings.HasSuffix(strings.TrimRight(line, " \t"), "\\") {
			trimmed := strings.TrimRight(line, " \t")
			buf.WriteString(strings.TrimSuffix(trimmed, "\\"))
			buf.WriteByte(' ')
			joining = true
			continue
		}
		buf.WriteString(line)
		logical := buf.String()
		buf.Reset()
		joining = false
		out = appendDirective(out, logical)
	}
	if joining { // trailing '\' with no final line
		out = appendDirective(out, buf.String())
	}
	return out
}

// appendDirective normalizes and classifies one logical line. Blank/comment
// lines contribute nothing; a well-formed line becomes a mapped directive;
// anything else is preserved as a passthrough (template == "").
func appendDirective(out []preseedDirective, logical string) []preseedDirective {
	collapsed := strings.Join(strings.Fields(logical), " ")
	if collapsed == "" || strings.HasPrefix(collapsed, "#") {
		return out
	}
	fields := strings.SplitN(collapsed, " ", 4)
	if len(fields) < 3 {
		return append(out, preseedDirective{raw: collapsed})
	}
	// Template must contain "/" to be a valid preseed directive
	if !strings.Contains(fields[1], "/") {
		return append(out, preseedDirective{raw: collapsed})
	}
	d := preseedDirective{owner: fields[0], template: fields[1], dtype: fields[2], raw: collapsed}
	if len(fields) == 4 {
		d.value = fields[3]
	}
	return append(out, d)
}

// marshalDebianConfig renders the output view as debianconfig YAML with a
// provenance header. Unset fields emit nothing (omitempty + pointer nesting).
func marshalDebianConfig(o dcOutput, warnings []string) ([]byte, error) {
	body, err := yaml.Marshal(o)
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString("# generated by booty convert-preseed\n")
	if len(warnings) > 0 {
		b.WriteString("# round-trip warnings (review these fields):\n")
		for _, w := range warnings {
			b.WriteString("#   - ")
			b.WriteString(w)
			b.WriteByte('\n')
		}
	}
	b.Write(body)
	return b.Bytes(), nil
}
