package http

import (
	"bytes"
	"strings"

	yaml "go.yaml.in/yaml/v4"
)

type preseedDirective struct {
	owner    string
	template string
	dtype    string
	value    string
	raw      string
}

// dcOutput is the dedicated emit-only output view (NOT debianConfigSpec, whose
// scalars lack omitempty and whose sudoMode would emit `sudo: 0`).
type dcOutput struct {
	Hostname    string      `yaml:"hostname,omitempty"`
	Domain      string      `yaml:"domain,omitempty"`
	Locale      string      `yaml:"locale,omitempty"`
	Timezone    string      `yaml:"timezone,omitempty"`
	Keyboard    string      `yaml:"keyboard,omitempty"`
	Mirror      *dcMirror   `yaml:"mirror,omitempty"`
	Network     *dcNetwork  `yaml:"network,omitempty"`
	Accounts    *dcAccounts `yaml:"accounts,omitempty"`
	Packages    []string    `yaml:"packages,omitempty"`
	Disk        *dcDisk     `yaml:"disk,omitempty"`
	LateCommand string      `yaml:"late_command,omitempty"`
	RawPreseed  string      `yaml:"raw_preseed,omitempty"`
}

type dcMirror struct {
	Hostname  string `yaml:"hostname,omitempty"`
	Directory string `yaml:"directory,omitempty"`
	Proxy     string `yaml:"proxy,omitempty"`
}

type dcNetwork struct {
	Interface string    `yaml:"interface,omitempty"`
	Static    *dcStatic `yaml:"static,omitempty"`
}

type dcStatic struct {
	Address     string   `yaml:"address,omitempty"`
	Netmask     string   `yaml:"netmask,omitempty"`
	Gateway     string   `yaml:"gateway,omitempty"`
	Nameservers []string `yaml:"nameservers,omitempty"`
}

type dcAccounts struct {
	RootPasswordHash string  `yaml:"root_password_hash,omitempty"`
	User             *dcUser `yaml:"user,omitempty"`
}

type dcUser struct {
	Fullname          string   `yaml:"fullname,omitempty"`
	Username          string   `yaml:"username,omitempty"`
	PasswordHash      string   `yaml:"password_hash,omitempty"`
	SSHAuthorizedKeys []string `yaml:"ssh_authorized_keys,omitempty"`
	// sudo intentionally absent: reverse keeps ssh/sudo verbatim in late_command.
}

type dcDisk struct {
	Devices      []string `yaml:"devices,omitempty"`
	RAID         string   `yaml:"raid,omitempty"`
	Layout       string   `yaml:"layout,omitempty"`
	Filesystem   string   `yaml:"filesystem,omitempty"`
	BootDegraded *bool    `yaml:"boot_degraded,omitempty"`
	ExpertRecipe string   `yaml:"expert_recipe,omitempty"`
}

// parsePreseed splits a flat d-i preseed into logical directives. It joins
// backslash line-continuations, drops blank lines and '#' comments, and splits
// each logical line into owner/template/type/value. A line that does not fit the
// `owner template type [value]` grammar is preserved verbatim as a passthrough
// directive (template == "") so nothing is ever dropped.
func parsePreseed(src []byte) []preseedDirective {
	var out []preseedDirective
	var buf strings.Builder
	joining := false
	for _, raw := range strings.Split(string(src), "\n") {
		line := raw
		// A physical line ending in '\' continues onto the next.
		if strings.HasSuffix(strings.TrimRight(line, " \t"), "\\") {
			trimmed := strings.TrimRight(line, " \t")
			buf.WriteString(strings.TrimSuffix(trimmed, "\\"))
			buf.WriteByte(' ')
			joining = true
			continue
		}
		buf.WriteString(line)
		logical := buf.String()
		buf.Reset()
		joining = false
		out = appendDirective(out, logical)
	}
	if joining { // trailing '\' with no final line
		out = appendDirective(out, buf.String())
	}
	return out
}

// appendDirective normalizes and classifies one logical line. Blank/comment
// lines contribute nothing; a well-formed line becomes a mapped directive;
// anything else is preserved as a passthrough (template == "").
func appendDirective(out []preseedDirective, logical string) []preseedDirective {
	collapsed := strings.Join(strings.Fields(logical), " ")
	if collapsed == "" || strings.HasPrefix(collapsed, "#") {
		return out
	}
	fields := strings.SplitN(collapsed, " ", 4)
	if len(fields) < 3 {
		return append(out, preseedDirective{raw: collapsed})
	}
	// Template must contain "/" to be a valid preseed directive
	if !strings.Contains(fields[1], "/") {
		return append(out, preseedDirective{raw: collapsed})
	}
	d := preseedDirective{owner: fields[0], template: fields[1], dtype: fields[2], raw: collapsed}
	if len(fields) == 4 {
		d.value = fields[3]
	}
	return append(out, d)
}

// marshalDebianConfig renders the output view as debianconfig YAML with a
// provenance header. Unset fields emit nothing (omitempty + pointer nesting).
func marshalDebianConfig(o dcOutput, warnings []string) ([]byte, error) {
	body, err := yaml.Marshal(o)
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString("# generated by booty convert-preseed\n")
	if len(warnings) > 0 {
		b.WriteString("# round-trip warnings (review these fields):\n")
		for _, w := range warnings {
			b.WriteString("#   - ")
			b.WriteString(w)
			b.WriteByte('\n')
		}
	}
	b.Write(body)
	return b.Bytes(), nil
}

// mapScalars maps every non-disk directive it recognizes into a dcOutput and
// returns the directives it did NOT consume (unknown lines + the whole disk
// group + orphaned static fields) as remainder for later handling. Network
// static fields are only mapped when the static markers are present; otherwise
// they fall to remainder (the schema has no DHCP+custom-DNS shape).
func mapScalars(dirs []preseedDirective) (dcOutput, []preseedDirective) {
	var o dcOutput
	var remainder []preseedDirective

	// Partition network directives so static coherence can be judged as a unit.
	staticMarkers := false
	for _, d := range dirs {
		if d.template == "netcfg/disable_autoconfig" && d.value == "true" || d.template == "netcfg/confirm_static" {
			staticMarkers = true
		}
	}

	ensureNet := func() *dcNetwork {
		if o.Network == nil {
			o.Network = &dcNetwork{}
		}
		return o.Network
	}
	ensureStatic := func() *dcStatic {
		n := ensureNet()
		if n.Static == nil {
			n.Static = &dcStatic{}
		}
		return n.Static
	}
	ensureAcct := func() *dcAccounts {
		if o.Accounts == nil {
			o.Accounts = &dcAccounts{}
		}
		return o.Accounts
	}
	ensureUser := func() *dcUser {
		a := ensureAcct()
		if a.User == nil {
			a.User = &dcUser{}
		}
		return a.User
	}
	ensureMirror := func() *dcMirror {
		if o.Mirror == nil {
			o.Mirror = &dcMirror{}
		}
		return o.Mirror
	}

	for _, d := range dirs {
		if d.template == "" || isDiskDirective(d.template) {
			remainder = append(remainder, d) // passthrough + disk group handled later
			continue
		}
		switch d.template {
		case "debian-installer/locale":
			o.Locale = d.value
		case "keyboard-configuration/xkb-keymap":
			o.Keyboard = d.value
		case "netcfg/get_hostname":
			o.Hostname = d.value
		case "netcfg/get_domain":
			o.Domain = d.value
		case "netcfg/choose_interface":
			ensureNet().Interface = d.value
		case "time/zone":
			o.Timezone = d.value
		case "mirror/http/hostname":
			ensureMirror().Hostname = d.value
		case "mirror/http/directory":
			ensureMirror().Directory = d.value
		case "mirror/http/proxy":
			ensureMirror().Proxy = d.value
		case "mirror/country":
			// booty re-emits `manual` when a mirror block is present; consumed, no field.
		case "passwd/root-password-crypted":
			ensureAcct().RootPasswordHash = d.value
		case "passwd/root-login", "passwd/make-user":
			// booleans implied by the presence of the hashes/user; consumed, no field.
		case "passwd/username":
			ensureUser().Username = d.value
		case "passwd/user-fullname":
			ensureUser().Fullname = d.value
		case "passwd/user-password-crypted":
			ensureUser().PasswordHash = d.value
		case "pkgsel/include":
			o.Packages = strings.Fields(d.value)
		case "preseed/late_command":
			o.LateCommand = d.value
		case "netcfg/disable_autoconfig", "netcfg/confirm_static":
			// static markers; consumed only when we actually build a static block.
			if !staticMarkers {
				remainder = append(remainder, d)
			}
		case "netcfg/get_ipaddress", "netcfg/get_netmask", "netcfg/get_gateway", "netcfg/get_nameservers":
			if !staticMarkers {
				remainder = append(remainder, d) // orphaned: DHCP + custom DNS, no structured home
				continue
			}
			s := ensureStatic()
			switch d.template {
			case "netcfg/get_ipaddress":
				s.Address = d.value
			case "netcfg/get_netmask":
				s.Netmask = d.value
			case "netcfg/get_gateway":
				s.Gateway = d.value
			case "netcfg/get_nameservers":
				s.Nameservers = strings.Fields(d.value)
			}
		default:
			remainder = append(remainder, d)
		}
	}
	return o, remainder
}

// isDiskDirective reports whether a template belongs to the disk/partman group.
// grub-installer/* is included so the UEFI-mirror shape's
// grub-installer/force-efi-extra-removable (debiangen.go:584) is consumed with
// the group and cannot leak into raw_preseed (SGE B1).
func isDiskDirective(template string) bool {
	switch {
	case strings.HasPrefix(template, "partman"): // partman, partman-auto, partman-auto-raid, partman-lvm, partman-md, partman-efi, partman-basicfilesystems
		return true
	case strings.HasPrefix(template, "mdadm/"):
		return true
	case strings.HasPrefix(template, "grub-installer/"): // bootdev + force-efi-extra-removable
		return true
	}
	return false
}

// recognizeDisk matches the disk group against the shapes booty's forward
// generator emits (debiangen.go preseedTemplateText) plus canonical d-i atomic.
// All-or-nothing: on a match it returns a fully-populated *dcDisk and ok==true
// (every group line is considered consumed); otherwise ok==false and the caller
// keeps the whole group in raw_preseed. Recognition is driven by a template→value
// index so it is order-independent.
func recognizeDisk(group []preseedDirective) (*dcDisk, bool) {
	idx := map[string]string{}
	for _, d := range group {
		if d.template != "" {
			idx[d.template] = d.value
		}
	}
	devices := strings.Fields(idx["partman-auto/disk"])
	if len(devices) == 0 {
		return nil, false // every booty disk shape sets partman-auto/disk
	}
	method := idx["partman-auto/method"]

	switch method {
	case "regular":
		// atomic (curated plain/xfs) OR expert_recipe.
		if recipe, ok := idx["partman-auto/expert_recipe"]; ok {
			d := &dcDisk{Devices: devices, ExpertRecipe: recipe}
			// debiangen.go emits mdadm/boot_degraded on the expert path only when
			// the operator set boot_degraded (BootDegradedSet gate), so recover it
			// when present to keep an explicit value round-trip-faithful.
			if bd, ok := idx["mdadm/boot_degraded"]; ok {
				v := bd == "true"
				d.BootDegraded = &v
			}
			return d, true
		}
		if idx["partman-auto/choose_recipe"] == "atomic" {
			d := &dcDisk{Devices: devices, Layout: "plain", Filesystem: idx["partman/default_filesystem"]}
			return d, true
		}
		return nil, false
	case "lvm":
		d := &dcDisk{Devices: devices, Layout: "lvm"}
		if idx["partman/default_filesystem"] != "" {
			d.Filesystem = idx["partman/default_filesystem"]
		}
		return d, true
	case "raid":
		// booty's UEFI mirror. Distinguish plain vs lvm by the partman-lvm marker
		// and recover boot_degraded. Filesystem is intentionally left unset for
		// BOTH raid variants (mirror and mirror+lvm): the fs lives in the raid
		// recipe tokens, not a partman/default_filesystem line, and Task 5/6
		// round-trip verification confirms the re-render is equivalent.
		d := &dcDisk{Devices: devices, RAID: "mirror"}
		if _, lvm := idx["partman-lvm/confirm"]; lvm {
			d.Layout = "lvm"
		} else {
			d.Layout = "plain"
		}
		if bd, ok := idx["mdadm/boot_degraded"]; ok {
			v := bd == "true"
			d.BootDegraded = &v
		}
		return d, true
	}
	return nil, false
}
