package http

import (
	"bytes"
	"fmt"
	"slices"
	"strings"

	yaml "go.yaml.in/yaml/v4"
)

type preseedDirective struct {
	owner    string
	template string
	dtype    string
	value    string
	raw      string
}

// dcOutput is the dedicated emit-only output view (NOT debianConfigSpec, whose
// scalars lack omitempty and whose sudoMode would emit `sudo: 0`).
type dcOutput struct {
	Hostname    string      `yaml:"hostname,omitempty"`
	Domain      string      `yaml:"domain,omitempty"`
	Locale      string      `yaml:"locale,omitempty"`
	Timezone    string      `yaml:"timezone,omitempty"`
	Keyboard    string      `yaml:"keyboard,omitempty"`
	Mirror      *dcMirror   `yaml:"mirror,omitempty"`
	Network     *dcNetwork  `yaml:"network,omitempty"`
	Accounts    *dcAccounts `yaml:"accounts,omitempty"`
	Packages    []string    `yaml:"packages,omitempty"`
	Disk        *dcDisk     `yaml:"disk,omitempty"`
	LateCommand string      `yaml:"late_command,omitempty"`
	RawPreseed  string      `yaml:"raw_preseed,omitempty"`
}

type dcMirror struct {
	Hostname  string `yaml:"hostname,omitempty"`
	Directory string `yaml:"directory,omitempty"`
	Proxy     string `yaml:"proxy,omitempty"`
}

type dcNetwork struct {
	Interface string    `yaml:"interface,omitempty"`
	Static    *dcStatic `yaml:"static,omitempty"`
}

type dcStatic struct {
	Address     string   `yaml:"address,omitempty"`
	Netmask     string   `yaml:"netmask,omitempty"`
	Gateway     string   `yaml:"gateway,omitempty"`
	Nameservers []string `yaml:"nameservers,omitempty"`
}

type dcAccounts struct {
	RootPasswordHash string  `yaml:"root_password_hash,omitempty"`
	User             *dcUser `yaml:"user,omitempty"`
}

type dcUser struct {
	Fullname          string   `yaml:"fullname,omitempty"`
	Username          string   `yaml:"username,omitempty"`
	PasswordHash      string   `yaml:"password_hash,omitempty"`
	SSHAuthorizedKeys []string `yaml:"ssh_authorized_keys,omitempty"`
	// sudo intentionally absent: reverse keeps ssh/sudo verbatim in late_command.
}

type dcDisk struct {
	Devices      []string `yaml:"devices,omitempty"`
	RAID         string   `yaml:"raid,omitempty"`
	Layout       string   `yaml:"layout,omitempty"`
	Filesystem   string   `yaml:"filesystem,omitempty"`
	BootDegraded *bool    `yaml:"boot_degraded,omitempty"`
	ExpertRecipe string   `yaml:"expert_recipe,omitempty"`
}

// parsePreseed splits a flat d-i preseed into logical directives. It joins
// backslash line-continuations, drops blank lines and '#' comments, and splits
// each logical line into owner/template/type/value. A line that does not fit the
// `owner template type [value]` grammar is preserved verbatim as a passthrough
// directive (template == "") so nothing is ever dropped.
func parsePreseed(src []byte) []preseedDirective {
	var out []preseedDirective
	var buf strings.Builder
	joining := false
	// Normalize CRLF -> LF up front so a trailing '\' continuation marker is
	// never hidden behind a '\r' on Windows-authored preseed files.
	normalized := strings.ReplaceAll(string(src), "\r\n", "\n")
	for _, raw := range strings.Split(normalized, "\n") {
		line := raw
		// A physical line ending in '\' continues onto the next.
		trimmed := strings.TrimRight(line, " \t")
		if strings.HasSuffix(trimmed, "\\") {
			buf.WriteString(strings.TrimSuffix(trimmed, "\\"))
			buf.WriteByte(' ')
			joining = true
			continue
		}
		buf.WriteString(line)
		logical := buf.String()
		buf.Reset()
		joining = false
		out = appendDirective(out, logical)
	}
	if joining { // trailing '\' with no final line
		out = appendDirective(out, buf.String())
	}
	return out
}

// appendDirective normalizes and classifies one logical line. Blank/comment
// lines contribute nothing; a well-formed line becomes a mapped directive;
// anything else is preserved as a passthrough (template == "").
func appendDirective(out []preseedDirective, logical string) []preseedDirective {
	collapsed := strings.Join(strings.Fields(logical), " ")
	if collapsed == "" || strings.HasPrefix(collapsed, "#") {
		return out
	}
	fields := strings.SplitN(collapsed, " ", 4)
	if len(fields) < 3 {
		return append(out, preseedDirective{raw: collapsed})
	}
	// Template must contain "/" to be a valid preseed directive
	if !strings.Contains(fields[1], "/") {
		return append(out, preseedDirective{raw: collapsed})
	}
	d := preseedDirective{owner: fields[0], template: fields[1], dtype: fields[2], raw: collapsed}
	if len(fields) == 4 {
		d.value = fields[3]
	}
	return append(out, d)
}

// marshalDebianConfig renders the output view as debianconfig YAML with a
// provenance header. Unset fields emit nothing (omitempty + pointer nesting).
func marshalDebianConfig(o dcOutput, warnings []string) ([]byte, error) {
	body, err := yaml.Marshal(o)
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString("# generated by booty convert-preseed\n")
	if len(warnings) > 0 {
		b.WriteString("# round-trip warnings (review these fields):\n")
		for _, w := range warnings {
			b.WriteString("#   - ")
			b.WriteString(w)
			b.WriteByte('\n')
		}
	}
	b.Write(body)
	return b.Bytes(), nil
}

// Note (DRY): the preseed directive-name vocabulary recognized below is
// necessarily duplicated from debiangen.go's forward template
// (preseedTemplateText) — there is no single source both a text/template blob
// and a parser can share. verifyRoundTrip is the intentional guard against
// silent drift between the two: any directive this file stops recognizing (or
// mis-recognizes) surfaces as a round-trip warning rather than a silent bug.

// mapScalars maps every non-disk directive it recognizes into a dcOutput and
// returns the directives it did NOT consume (unknown lines + the whole disk
// group + orphaned static fields) as remainder for later handling. Network
// static fields are only mapped when the static markers are present; otherwise
// they fall to remainder (the schema has no DHCP+custom-DNS shape).
func mapScalars(dirs []preseedDirective) (dcOutput, []preseedDirective) {
	var o dcOutput
	var remainder []preseedDirective

	// Partition network directives so static coherence can be judged as a unit.
	staticMarkers := false
	for _, d := range dirs {
		if d.template == "netcfg/disable_autoconfig" && d.value == "true" || d.template == "netcfg/confirm_static" {
			staticMarkers = true
		}
	}

	ensureNet := func() *dcNetwork {
		if o.Network == nil {
			o.Network = &dcNetwork{}
		}
		return o.Network
	}
	ensureStatic := func() *dcStatic {
		n := ensureNet()
		if n.Static == nil {
			n.Static = &dcStatic{}
		}
		return n.Static
	}
	ensureAcct := func() *dcAccounts {
		if o.Accounts == nil {
			o.Accounts = &dcAccounts{}
		}
		return o.Accounts
	}
	ensureUser := func() *dcUser {
		a := ensureAcct()
		if a.User == nil {
			a.User = &dcUser{}
		}
		return a.User
	}
	ensureMirror := func() *dcMirror {
		if o.Mirror == nil {
			o.Mirror = &dcMirror{}
		}
		return o.Mirror
	}

	for _, d := range dirs {
		if d.template == "" || isDiskDirective(d.template) {
			remainder = append(remainder, d) // passthrough + disk group handled later
			continue
		}
		switch d.template {
		case "debian-installer/locale":
			o.Locale = d.value
		case "keyboard-configuration/xkb-keymap":
			o.Keyboard = d.value
		case "netcfg/get_hostname":
			o.Hostname = d.value
		case "netcfg/get_domain":
			o.Domain = d.value
		case "netcfg/choose_interface":
			ensureNet().Interface = d.value
		case "time/zone":
			o.Timezone = d.value
		case "mirror/http/hostname":
			ensureMirror().Hostname = d.value
		case "mirror/http/directory":
			ensureMirror().Directory = d.value
		case "mirror/http/proxy":
			ensureMirror().Proxy = d.value
		case "mirror/country":
			// booty only ever emits `manual` (mirror block present); consumed, no
			// field. Any other value is a hand-written preseed choice we don't
			// model structurally, so let it fall to remainder/raw_preseed instead
			// of silently dropping it.
			if d.value != "manual" {
				remainder = append(remainder, d)
			}
		case "passwd/root-password-crypted":
			ensureAcct().RootPasswordHash = d.value
		case "passwd/root-login", "passwd/make-user":
			// booleans implied by the presence of the hashes/user; consumed, no field.
		case "passwd/username":
			ensureUser().Username = d.value
		case "passwd/user-fullname":
			ensureUser().Fullname = d.value
		case "passwd/user-password-crypted":
			ensureUser().PasswordHash = d.value
		case "pkgsel/include":
			o.Packages = strings.Fields(d.value)
		case "preseed/late_command":
			o.LateCommand = d.value
		case "netcfg/disable_autoconfig", "netcfg/confirm_static":
			// static markers; consumed only when we actually build a static block.
			if !staticMarkers {
				remainder = append(remainder, d)
			}
		case "netcfg/get_ipaddress", "netcfg/get_netmask", "netcfg/get_gateway", "netcfg/get_nameservers":
			if !staticMarkers {
				remainder = append(remainder, d) // orphaned: DHCP + custom DNS, no structured home
				continue
			}
			s := ensureStatic()
			switch d.template {
			case "netcfg/get_ipaddress":
				s.Address = d.value
			case "netcfg/get_netmask":
				s.Netmask = d.value
			case "netcfg/get_gateway":
				s.Gateway = d.value
			case "netcfg/get_nameservers":
				s.Nameservers = strings.Fields(d.value)
			}
		default:
			remainder = append(remainder, d)
		}
	}
	return o, remainder
}

// isDiskDirective reports whether a template belongs to the disk/partman group.
// grub-installer/* is included so the UEFI-mirror shape's
// grub-installer/force-efi-extra-removable (debiangen.go:584) is consumed with
// the group and cannot leak into raw_preseed (SGE B1).
func isDiskDirective(template string) bool {
	switch {
	case strings.HasPrefix(template, "partman"): // partman, partman-auto, partman-auto-raid, partman-lvm, partman-md, partman-efi, partman-basicfilesystems
		return true
	case strings.HasPrefix(template, "mdadm/"):
		return true
	case strings.HasPrefix(template, "grub-installer/"): // bootdev + force-efi-extra-removable
		return true
	}
	return false
}

// recognizeDisk matches the disk group against the shapes booty's forward
// generator emits (debiangen.go preseedTemplateText) plus canonical d-i atomic.
// All-or-nothing: on a match it returns a fully-populated *dcDisk and ok==true
// (every group line is considered consumed); otherwise ok==false and the caller
// keeps the whole group in raw_preseed. Recognition is driven by a template→value
// index so it is order-independent.
func recognizeDisk(group []preseedDirective) (*dcDisk, bool) {
	idx := map[string]string{}
	for _, d := range group {
		if d.template != "" {
			idx[d.template] = d.value
		}
	}
	devices := strings.Fields(idx["partman-auto/disk"])
	if len(devices) == 0 {
		return nil, false // every booty disk shape sets partman-auto/disk
	}
	method := idx["partman-auto/method"]

	switch method {
	case "regular":
		// atomic (curated plain/xfs) OR expert_recipe.
		if recipe, ok := idx["partman-auto/expert_recipe"]; ok {
			d := &dcDisk{Devices: devices, ExpertRecipe: recipe}
			// debiangen.go emits mdadm/boot_degraded on the expert path only when
			// the operator set boot_degraded (BootDegradedSet gate), so recover it
			// when present to keep an explicit value round-trip-faithful.
			if bd, ok := idx["mdadm/boot_degraded"]; ok {
				v := bd == "true"
				d.BootDegraded = &v
			}
			return d, true
		}
		if idx["partman-auto/choose_recipe"] == "atomic" {
			d := &dcDisk{Devices: devices, Layout: "plain", Filesystem: idx["partman/default_filesystem"]}
			return d, true
		}
		return nil, false
	case "lvm":
		d := &dcDisk{Devices: devices, Layout: "lvm"}
		if idx["partman/default_filesystem"] != "" {
			d.Filesystem = idx["partman/default_filesystem"]
		}
		return d, true
	case "raid":
		// booty's UEFI mirror. Distinguish plain vs lvm by the partman-lvm marker
		// and recover boot_degraded. The filesystem is NOT in a
		// partman/default_filesystem line for either raid variant — it is
		// embedded inside the raid recipe tokens themselves (debiangen.go:579,
		// :582), so recover it from there: raidPlainFilesystem /
		// raidLVMFilesystem locate the operator's fs token by scanning the
		// relevant recipe's whitespace-collapsed fields.
		d := &dcDisk{Devices: devices, RAID: "mirror"}
		if _, lvm := idx["partman-lvm/confirm"]; lvm {
			d.Layout = "lvm"
			if fs := raidLVMFilesystem(idx["partman-auto/expert_recipe"]); fs != "" {
				d.Filesystem = fs
			}
		} else {
			d.Layout = "plain"
			if fs := raidPlainFilesystem(idx["partman-auto-raid/recipe"]); fs != "" {
				d.Filesystem = fs
			}
		}
		if bd, ok := idx["mdadm/boot_degraded"]; ok {
			v := bd == "true"
			d.BootDegraded = &v
		}
		return d, true
	}
	return nil, false
}

// raidPlainFilesystem recovers the root filesystem from a plain-mirror
// partman-auto-raid/recipe value (debiangen.go:582: `... {fs} / {RootParts} .`).
// The root entry is the only one whose mountpoint token is the standalone "/"
// (the /boot entry's token is "/boot", a different string); the fs is the
// field immediately preceding it.
func raidPlainFilesystem(recipe string) string {
	fields := strings.Fields(recipe)
	for i, f := range fields {
		if f == "/" && i > 0 {
			return fields[i-1]
		}
	}
	return ""
}

// raidLVMFilesystem recovers the root filesystem from an lvm-mirror
// partman-auto/expert_recipe value (debiangen.go:579: `... filesystem{ {fs} } ...`).
// The lvm mirror's partman-auto-raid/recipe root entry is `lvm -` and carries
// no fs (raidPlainFilesystem does not apply); the fs instead lives in the
// auto-generated "multiraid" expert_recipe's filesystem{} clause.
func raidLVMFilesystem(recipe string) string {
	fields := strings.Fields(recipe)
	for i, f := range fields {
		if f == "filesystem{" && i+1 < len(fields) {
			return fields[i+1]
		}
	}
	return ""
}

// normalizeDirectives reduces a preseed to a sorted set of owner-stripped,
// whitespace-collapsed logical directives — the round-trip comparison oracle.
// Reusing parsePreseed guarantees the SAME continuation-joining and whitespace
// collapse on both sides (SGE B3), so a flattened single-line expert_recipe
// compares equal to a multi-line hand-written one.
func normalizeDirectives(src []byte) []string {
	var out []string
	for _, d := range parsePreseed(src) {
		if d.template == "" {
			if d.raw != "" {
				out = append(out, d.raw) // passthrough line, compared verbatim (already collapsed)
			}
			continue
		}
		out = append(out, strings.TrimSpace(d.template+" "+d.dtype+" "+d.value))
	}
	slices.Sort(out)
	return out
}

// ConvertPreseedToDebianConfig converts a flat d-i preseed into structured
// debianconfig YAML (design §3). Recognized scalar + disk directives become
// structured fields; everything else is preserved verbatim in raw_preseed. It
// always emits (verify+warn), returning warnings for anything that did not
// round-trip through translateDebianConfig.
func ConvertPreseedToDebianConfig(preseed []byte) ([]byte, []string, error) {
	dirs := parsePreseed(preseed)
	o, remainder := mapScalars(dirs)

	// Disk group: all-or-nothing. Split remainder into disk vs the rest.
	var diskGroup, rest []preseedDirective
	for _, d := range remainder {
		if isDiskDirective(d.template) {
			diskGroup = append(diskGroup, d)
		} else {
			rest = append(rest, d)
		}
	}
	var mirrorDevices []string
	if len(diskGroup) > 0 {
		if disk, ok := recognizeDisk(diskGroup); ok {
			o.Disk = disk
			if disk.RAID == "mirror" {
				mirrorDevices = disk.Devices
			}
		} else {
			for _, d := range diskGroup { // unrecognized → raw_preseed verbatim
				rest = append(rest, d)
			}
		}
	}

	// B2: when the mirror disk is recognized, booty's forward gen will regenerate
	// the ESP-sync fragment into late_command; strip the identical fragment from
	// the captured late_command so it isn't double-emitted (false round-trip warn).
	if mirrorDevices != nil && o.LateCommand != "" {
		o.LateCommand = stripESPSync(o.LateCommand, mirrorDevices)
	}

	// raw_preseed remainder: unknown + malformed + unrecognized-disk lines, verbatim.
	var rawLines []string
	for _, d := range rest {
		rawLines = append(rawLines, d.raw)
	}
	o.RawPreseed = strings.Join(rawLines, "\n")

	body, err := marshalDebianConfig(o, nil)
	if err != nil {
		return nil, nil, err
	}
	warnings := verifyRoundTrip(preseed, body)
	out, err := marshalDebianConfig(o, warnings) // re-marshal with the warnings header
	if err != nil {
		return nil, nil, err
	}
	return out, warnings, nil
}

// stripESPSync removes the deterministic espSyncLateCommand(devices) fragment
// from a captured late_command (B2). The fragment is reconstructable from the
// recovered mirror device list. Remaining "; "-separated commands are preserved.
//
// The fragment is normalized with the SAME whitespace collapse parsePreseed
// applies to the captured late_command (strings.Fields + single-space Join)
// before the ReplaceAll, so a freshly-generated fragment matches the captured
// form even if either side ever grows incidental multi-space/tab runs.
func stripESPSync(lateCommand string, devices []string) string {
	frag := espSyncLateCommand(devices)
	if frag == "" {
		return lateCommand
	}
	frag = strings.Join(strings.Fields(frag), " ") // match parsePreseed's whitespace collapse
	s := strings.ReplaceAll(lateCommand, frag, "")
	// Removing a sandwiched fragment can leave an empty segment between two
	// " ; " separators; rebuild from the non-empty segments so the result is
	// always a clean " ; "-joined command list (handles sole/leading/trailing/
	// sandwiched fragments uniformly). Split ONLY on the exact " ; " the forward
	// generator uses, never a bare ";", so an operator command with an inline
	// semicolon is not broken.
	var kept []string
	for _, seg := range strings.Split(s, " ; ") {
		if t := strings.TrimSpace(seg); t != "" {
			kept = append(kept, t)
		}
	}
	return strings.Join(kept, " ; ")
}

// verifyRoundTrip re-renders the produced debianconfig YAML and diffs it against
// the original preseed. A re-render error (SGE B4) degrades to a warning, never a
// failure. Returns human-readable warnings for the symmetric set difference.
func verifyRoundTrip(input, produced []byte) []string {
	rendered, err := translateDebianConfig(produced)
	if err != nil {
		return []string{fmt.Sprintf("produced YAML did not re-render: %v; review the structured fields", err)}
	}
	in := normalizeDirectives(input)
	out := normalizeDirectives(rendered)
	inSet := map[string]bool{}
	for _, s := range in {
		inSet[s] = true
	}
	outSet := map[string]bool{}
	for _, s := range out {
		outSet[s] = true
	}
	var warnings []string
	for _, s := range in {
		if !outSet[s] {
			warnings = append(warnings, "input directive not reproduced: "+s)
		}
	}
	for _, s := range out {
		if !inSet[s] {
			warnings = append(warnings, "converter added a directive not in input: "+s)
		}
	}
	return warnings
}
