package http

import (
	"reflect"
	"strings"
	"testing"
)

func TestParsePreseedBasicDirective(t *testing.T) {
	got := parsePreseed([]byte("d-i debian-installer/locale string en_US\n"))
	want := []preseedDirective{{owner: "d-i", template: "debian-installer/locale", dtype: "string", value: "en_US", raw: "d-i debian-installer/locale string en_US"}}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("parsePreseed = %#v, want %#v", got, want)
	}
}

func TestParsePreseedJoinsContinuations(t *testing.T) {
	src := "d-i partman-auto/expert_recipe string \\\n    boot-root :: \\\n    500 . \n"
	got := parsePreseed([]byte(src))
	if len(got) != 1 {
		t.Fatalf("want 1 joined directive, got %d: %#v", len(got), got)
	}
	if got[0].template != "partman-auto/expert_recipe" {
		t.Fatalf("template = %q", got[0].template)
	}
	if want := "boot-root :: 500 ."; !contains(got[0].value, "boot-root :: ") || !contains(got[0].value, "500 .") {
		t.Fatalf("value did not join continuations: %q (want to contain %q)", got[0].value, want)
	}
}

func TestParsePreseedDropsCommentsAndBlanks(t *testing.T) {
	src := "# a comment\n\nd-i time/zone string UTC\n   \n"
	got := parsePreseed([]byte(src))
	if len(got) != 1 || got[0].template != "time/zone" {
		t.Fatalf("comments/blanks not dropped: %#v", got)
	}
}

func TestParsePreseedPreservesUnparseableAsPassthrough(t *testing.T) {
	got := parsePreseed([]byte("this is not a directive\n"))
	if len(got) != 1 || got[0].template != "" || got[0].raw != "this is not a directive" {
		t.Fatalf("unparseable line not preserved: %#v", got)
	}
}

func TestParsePreseedPackageOwner(t *testing.T) {
	got := parsePreseed([]byte("keyboard-configuration keyboard-configuration/xkb-keymap select us\n"))
	if len(got) != 1 || got[0].owner != "keyboard-configuration" || got[0].template != "keyboard-configuration/xkb-keymap" || got[0].value != "us" {
		t.Fatalf("package-owned directive misparsed: %#v", got)
	}
}

// contains is a tiny local helper to keep assertions readable.
func contains(s, sub string) bool { return strings.Contains(s, sub) }

func TestMarshalEmitsOnlySetFields(t *testing.T) {
	o := dcOutput{Hostname: "web01", Timezone: "UTC"}
	got, err := marshalDebianConfig(o, nil)
	if err != nil {
		t.Fatal(err)
	}
	s := string(got)
	if !contains(s, "hostname: web01") || !contains(s, "timezone: UTC") {
		t.Fatalf("missing set fields:\n%s", s)
	}
	for _, absent := range []string{"domain:", "locale:", "keyboard:", "mirror:", "network:", "accounts:", "disk:", "late_command:", "raw_preseed:", "sudo:"} {
		if contains(s, absent) {
			t.Fatalf("emitted an unset field %q:\n%s", absent, s)
		}
	}
}

func TestMarshalHeaderComment(t *testing.T) {
	got, _ := marshalDebianConfig(dcOutput{Hostname: "h"}, []string{"disk went to raw_preseed"})
	s := string(got)
	if !contains(s, "# generated by booty convert-preseed") {
		t.Fatalf("missing provenance header:\n%s", s)
	}
	if !contains(s, "disk went to raw_preseed") {
		t.Fatalf("warnings not surfaced in header:\n%s", s)
	}
}

func TestMarshalNestedPointerBlocksOmitWhenNil(t *testing.T) {
	o := dcOutput{Accounts: &dcAccounts{RootPasswordHash: "$6$x"}}
	s := string(mustMarshal(t, o))
	if !contains(s, "accounts:") || !contains(s, "root_password_hash: $6$x") {
		t.Fatalf("accounts block missing:\n%s", s)
	}
	if contains(s, "user:") {
		t.Fatalf("nil user pointer should be omitted:\n%s", s)
	}
}

func mustMarshal(t *testing.T, o dcOutput) []byte {
	t.Helper()
	b, err := marshalDebianConfig(o, nil)
	if err != nil {
		t.Fatal(err)
	}
	return b
}
